### PR TITLE
131 showusers

### PR DESCRIPTION
**Pull request by HanrichPotgieter**

### CODE REVIEW

**Comment by HanrichPotgieter** [comment]
Adding members still needs to be configured.

**Comment by ACalitz** [comment]
Lets fix the adding issue before the merge then we know its all working once the merge is complete

**Comment by HanrichPotgieter** [comment]
We will do that. Please just make sure your happy with the design.
Regards
Hanrich

**Comment by FrikkieSnyman** [comment]
Also, $scope is spelt $scop in the project-controller.js file, between lines 6 and 19. I'm not sure if this is intentional or not?

**Comment by HanrichPotgieter** [comment]
Will check it out tomorrow.  Thank you for the positive feedback.

**Comment by FrikkieSnyman** [comment]
@HanrichPotgieter I fixed the typo between lines 6 and 19. Since we don't have functional unit tests on this controller, please confirm the function's functionality

**Comment by HanrichPotgieter** [comment]
We can now add and remove members from a project. Please test and advise.

**Comment by HugoGreyvenstein** [comment]
I'm satisfied with the functionality, it really looks great. Good work.

**Comment by HugoGreyvenstein** [comment]
Oops! Forgot waffle.io closes.

Edit: It worked, though :\

**Pull request merged**
